config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' },
             skip: [:sessions]

  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign-in', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :account do
    namespace :admin do
      resources :issues, only: [:index, :edit, :update] do
        member do
          patch :approve, :decline, :close
        end
      end

      resources :users, only: [:index] do
        member do
          patch :toggle_ban
          patch :change_role
        end
      end

      resources :categories
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server, at: '/resque'
  end

  resources :categories, only: [:show]

  resources :issues, only: [:new, :index, :create, :show] do
    collection do
      get :map
      get :closed
    end
    member do
      get :popup
      post :upvote
      delete :downvote
    end
    post 'follow',   to: 'issues/socializations#follow'
    post 'unfollow', to: 'issues/socializations#unfollow'
    resources :comments, module: :issues, only: [:create, :index]
  end

  resources :comments, only: [:destroy]
  resources :users, only: [:show] do
    collection do
      get :ranking
    end
  end

  resources :events, only: [:show]

  get  'followees', to: 'issues#followees'
  get  'feed', to: 'feeds#common_feed'
  get  'user_feed', to: 'feeds#user_feed'
  get  'statistics', to: 'common_pages#statistics'
  get  ':page', to: 'pages#show', as: :static_pages
  root to: 'common_pages#home'
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  after_action :mark_as_read_loaded, only: [:user_feed]
  skip_before_action :require_active_user, only: [:user_feed, :common_feed]
  skip_before_action :authenticate_user!, only: [:common_feed]

  def user_feed
    current_user.check_notifications unless request.xhr?
    @events = current_user.events.ordered.page(params[:page]).per(3)
    respond_for_feed(@events)
  end

  def common_feed
    @events = Event.ordered.public_events.page(params[:page]).per(5)
    respond_for_feed(@events)
  end

  private

  def mark_as_read_loaded
    return unless request.xhr?
    notifications = current_user.unread_notifications_for(@events)
    notifications.update_all(readed: true)
  end

  def respond_for_feed(events)
    if request.xhr?
      response.headers['TotalPages'] = events.total_pages
      render partial: 'feeds/events/event_list'
    else
      render 'feeds/feed'
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def users_feed?
    params[:controller] == 'feeds' && params[:action] == 'user_feed'
  end

  def common_feed?
    params[:controller] == 'feeds' && params[:action] == 'common_feed'
  end
end

app/views/feeds/feed.html.slim
#heading-breadcrumbs
  .container
    .row.flex-row
      .col-md-7.col-sm-7.col-xs-7
        h2=title 'Останні оновлення'
      .col-md-5.col-sm-5.col-xs-5
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Останні оновлення
#content.feed
  .container
    .row
      - if users_feed? && !current_user.notifications.any?
        .col-xs-12
          h3 У вас поки немає жодних оновлень...
          = link_to 'Переглянути усі', feed_url
      - else
        #blog-listing-medium.col-md-12
          section.container.events_list.loaded_data_container
          #loader-block.col-xs-12.hidden
            = image_tag 'loader.gif', alt: 'Loader', id: 'loader-img',
                    class: 'img-responsive col-xs-2 col-xs-offset-5'
        = render 'events/event_details_modal'
- if common_feed? || (users_feed? && current_user.notifications.any?)
  javascript:
      $('document').ready(function () {
              init_infinity_scroll(1, window.location.href, true);
              init_event_details();
          }
      );