config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' },
             skip: [:sessions]

  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign-in', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :account do
    namespace :admin do
      resources :issues, only: [:index, :edit, :update] do
        member do
          patch :approve, :decline, :close
        end
      end

      resources :users, only: [:index] do
        member do
          patch :toggle_ban
          patch :change_role
        end
      end

      resources :categories
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server, at: '/resque'
  end

  resources :categories, only: [:show]

  resources :issues, only: [:new, :index, :create, :show] do
    collection do
      get :map
      get :closed
    end
    member do
      get :popup
      post :upvote
      delete :downvote
    end
    post 'follow',   to: 'issues/socializations#follow'
    post 'unfollow', to: 'issues/socializations#unfollow'
    resources :comments, module: :issues, only: [:create, :index]
  end

  resources :comments, only: [:destroy]
  resources :users, only: [:show] do
    collection do
      get :ranking
    end
  end

  resources :events, only: [:show]

  get  'followees', to: 'issues#followees'
  get  'feed', to: 'feeds#common_feed'
  get  'user_feed', to: 'feeds#user_feed'
  get  'statistics', to: 'common_pages#statistics'
  get  ':page', to: 'pages#show', as: :static_pages
  root to: 'common_pages#home'
end

app/models/issue.rb
# Encoding: utf-8
class Issue < ApplicationRecord
  include Rails.application.routes.url_helpers
  include AASM
  include Statuses
  include Facebook
  acts_as_followable

  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
  belongs_to :user
  belongs_to :category, counter_cache: :issues_count
  has_many :issue_attachments
  has_many :events

  accepts_nested_attributes_for :issue_attachments, allow_destroy: true
  enum status: STATUSES_SYM

  REGEXP_NAME = /\p{L}/
  REGEXP_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.\w+\z/i
  REGEXP_PHONE = /\A[ x0-9\+\(\)\-\.]+\z/

  validates :name, :address, :phone, :email, :category_id,
            :description, :user_id, :title,
            presence: true
  validates :location, presence: true,
                       unless: ->(obj) { lt_ln_present?(obj) }
  validates :name, length: { minimum: 4, maximum: 255 },
                   format: { with: REGEXP_NAME,
                             message: 'Ім\'я повинне містити лише літери' }
  validates :phone, length: { maximum: 50 },
                    format: { with: REGEXP_PHONE,
                              message: 'Номер телефону повинен містити лише
                              цифри' }
  validates :email, length: { maximum: 255 },
                    format: { with: REGEXP_EMAIL,
                              message: 'Адреса повинна бути справжньою' }
  validates :description, length: { minimum: 50, maximum: 3000 }
  validates :title, length: { minimum: 10, maximum: 80 }
  scope :ordered, -> { order(created_at: :desc) }
  scope :approved, -> { where(status: :opened) }
  scope :closed, -> { where(status: :closed) }
  scope :status, ->(a) { where(status: a) }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :declined
    state :opened
    state :closed

    event :approve do
      transitions from: :pending, to: :opened
    end

    event :decline do
      transitions from: :pending, to: :declined
    end

    event :close do
      transitions from: :opened, to: :closed
    end
  end

  geocoded_by :location
  after_validation :geocode,
                   if: ->(obj) { obj.location.present? && !obj.latitude? }
  reverse_geocoded_by :latitude, :longitude, address: :location
  after_validation :reverse_geocode,
                   if: ->(obj) { !obj.location.present? && lt_ln_present?(obj) }
  after_create :notify_support

  def lt_ln_present?(obj)
    obj.latitude.present? && obj.longitude.present?
  end

  def status_name
    STATUSES[status]
  end

  def self.status_attributes_for_select
    m_name = model_name.i18n_key
    statuses.map do |status, _|
      [I18n.t("activerecord.attributes.#{m_name}.statuses.#{status}"), status]
    end
  end

  def published?
    %w(opened closed).include? status
  end

  def self.moderation_list
    joins(:user).select('issues.*, users.first_name, users.last_name')
  end

  def self.find_issues(search_query)
    where('title ilike :arg OR users.last_name ilike :arg',
          arg: "%#{search_query}%")
  end

  def self.like(search_query)
    where('title ilike :arg OR description ilike :arg OR location ilike :arg',
          arg: "%#{search_query}%")
  end

  def can_read_when_unpublished?(user)
    user.admin? || user.moderator? || (self.user == user)
  end

  def can_read?(user)
    published? || can_read_when_unpublished?(user)
  end

  def first_attached_image
    issue_attachments.first_or_initialize.attachment
  end

  def notify_support
    IssueMailer.issue_created(id).deliver
  end

  def prepare_facebook_page
    FbGraph2::Page.new(ENV['FACEBOOK_GROUP_ID'],
                       access_token: ENV['FACEBOOK_GROUP_TOKEN'])
  end

  def self.statistics_for(period, group, scope)
    where(status: scope)
      .group_by_period(group, :created_at, range: period).count
  end

  def create_event(event)
    event.before_status = aasm.from_state
    event.after_status = aasm.to_state
    event.save!
  end
end

app/controllers/account/admin/issues_controller.rb
# Encoding: utf-8
# frozen_string_literal: true
module Account
  module Admin
    class IssuesController < ApplicationController
      before_action :admin_or_moderator?
      before_action :find_issue,
                    only: [:edit, :update, :approve, :close, :decline]
      skip_before_action :admin_or_moderator?, only: [:close]
      before_action :can_close?, only: [:close]

      def index
        issue_listing(Issue.moderation_list)
      end

      def edit; end

      def update
        if @issue.update_attributes(issues_params)
          flash[:success] = 'Звернення змінено!'
          @issue.post_to_facebook! if @issue.opened?
          redirect_to @issue
        else
          render 'edit'
        end
      end

      def approve
        if change_status_transaction(@issue, 'approve', event_params)
          @issue.post_to_facebook!
          redirect_to @issue, notice: 'Статус успішно змінений.'
        else
          redirect_to @issue, alert: 'Щось пішло не так, спробуйте ще раз...'
        end
      end

      def decline
        if change_status_transaction(@issue, 'decline', event_params)
          redirect_to @issue, notice: 'Статус успішно змінений.'
        else
          redirect_to @issue, alert: 'Щось пішло не так, спробуйте ще раз...'
        end
      end

      def close
        if change_status_transaction(@issue, 'close', event_params)
          redirect_to @issue, notice: 'Статус успішно змінений.'
        else
          redirect_to @issue, alert: 'Щось пішло не так, спробуйте ще раз...'
        end
      end

      private

      def change_status_transaction(issue, status, event_params)
        ActiveRecord::Base.transaction do
          issue.send("#{status}!")
          @event = build_event(issue, event_params)
          @event.save!
        end
      rescue ActiveRecord::RecordInvalid, AASM::InvalidTransition
        false
      end

      def build_event(issue, event_params)
        event = Event.new(event_params)
        event.issue = issue
        event.author_id = current_user.id
        event.before_status = issue.aasm.from_state
        event.after_status = issue.aasm.to_state
        event
      end

      def can_close?
        redirect_to @issue, error: 'Щось пішло не так, спробуйте ще раз...'\
                                          unless current_user.can_close?(@issue)
      end

      def find_issue
        @issue = Issue.find(params[:id])
      end

      def issues_params
        params.require(:issue).permit(:category_id, :location, :latitude,
                                      :longitude)
      end

      def event_params
        params.require(:event).permit(:description, :image)
      end
    end
  end
end

app/controllers/issues/comments_controller.rb
module Issues
  class CommentsController < ::CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = Issue.find(params[:issue_id])
    end
  end
end

app/controllers/issues/socializations_controller.rb
# Encoding: utf-8
module Issues
  class SocializationsController < ApplicationController
    def follow
      @issue = Issue.find(params[:issue_id])
      if current_user.follow!(@issue)
        redirect_to @issue
      else
        redirect_to @issue,
                    alert: 'Щось пішло не так. Ви не змогли почати слідкування.'
      end
    end

    def unfollow
      @issue = Issue.find(params[:issue_id])
      if current_user.unfollow!(@issue)
        redirect_to @issue
      else
        redirect_to @issue,
                    alert: 'Щось пішло не так. Ви не змогли відписатися.'
      end
    end
  end
end

app/controllers/issues_controller.rb
# Encoding: utf-8
class IssuesController < ApplicationController
  helper IssuesHelper
  before_action :status_inspector, only: [:index]
  before_action :init_issue, only: [:show, :upvote, :downvote]
  skip_before_action :authenticate_user!, :require_active_user,
                     only: [:index, :show, :followees, :map, :popup]
  respond_to :html, :json

  def index
    @status = params[:status] || 'opened'
    issues_scope = Issue.ordered
                        .where(status: @status)
    issues_scope = issues_scope.like(params[:filter]) if params[:filter]
    smart_listing_create :issues,
                         issues_scope,
                         partial: 'issues/issue'
    @categories = Category.ordered_by_name
  end

  def new
    @issue = current_user.issues.new
  end

  def show
    @attachments = @issue.issue_attachments
    @voted = @issue.votes.where(user_id: current_user.id)
    @event = Event.new
    @events = @issue.events
    load_relevant_issues
  end

  def map
    @issues = Issue.select('id,latitude, longitude').approved
    respond_with(@issues)
  end

  def popup
    @issue = Issue.find(params[:id])
    respond_with(id: @issue.id,
                 title: @issue.title,
                 description: @issue.description,
                 created_at: l(@issue.created_at, format: :short),
                 img: @issue.first_attached_image)
  end

  def followees
    @issues = current_user.followees(Issue)
  end

  def create
    @issue = current_user.issues.new(issues_params)
    @issue = delete_empty_images(@issue)
    if @issue.save
      current_user.follow!(@issue)
      redirect_to @issue, notice: 'Звернення створене успішно!'
    else
      render 'new'
    end
  end

  def upvote
    @vote = @issue.votes.build user: current_user
    if @vote.save
      redirect_to @issue
    else
      redirect_to @issue, notice: 'Ви не змогли проголосувати'
    end
  end

  def downvote
    @vote = @issue.votes.find_by(user_id: current_user.id)
    if @vote.present?
      @issue.votes.destroy(@vote)
      redirect_to @issue
    else
      redirect_to @issue, notice: 'Ви уже забрали свій голос.'
    end
  end

  private

  def delete_empty_images(issue)
    filtered = issue.issue_attachments.to_ary.select do |a|
      a.attachment.to_s != '/images/fallback.jpg'
    end
    filtered ||= IssueAttachment.new
    issue.issue_attachments = filtered
    issue
  end

  def load_relevant_issues
    @relevant_issues = @issue.category.issues.where.not(id: @issue.id)
                             .order('random()').limit(4)
    redirect_back(fallback_location: root_path) unless \
                      @issue.can_read?(current_user)
  end

  def issues_params
    params.require(:issue).permit(:name, :address, :phone,
                                  :email,
                                  :category_id,
                                  :description,
                                  :location,
                                  :title,
                                  issue_attachments_attributes: [
                                    :attachment,
                                    :_destroy
                                  ])
  end

  def init_issue
    @issue = Issue.find(params[:id])
  end

  def status_inspector
    redirect_back(fallback_location: root_path) unless
      %w(opened closed).include?(params[:status]) || params[:status].blank?
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def get_stylized_status_style(status, text)
    type = case status
           when 'opened' then 'warning'
           when 'pending' then 'info'
           when 'declined' then 'danger'
           when 'closed' then 'success'
           end
    content_tag :span, text,
                class: "label label-#{type}"
  end

  def issue_map_url
    "//maps.googleapis.com/maps/api/staticmap?center=
     #{@issue.latitude},#{@issue.longitude}&markers=#{@issue.latitude},
     #{@issue.longitude}&zoom=17&size=640x350&key=#{ENV['GOOGLE_MAPS_API_KEY']}"
  end

  def status_control_link(text, path, style)
    button_tag text, class: "btn btn-#{style} btn-sm change_status_link",
                     method: :patch, 'data-target': '#change_status_form',
                     'data-toggle': 'modal', 'data-path': path
  end
end

app/views/issues/_breadcrumbs_index.html.slim
#heading-breadcrumbs
  .container
    .row.flex-row
      .col-md-7.col-sm-7.col-xs-7
        h2=title 'Перелік звернень'
      .col-md-5.col-sm-5.col-xs-5
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Звернення

app/views/issues/_edit_link.html.slim
-if current_user.admin?
  = link_to 'Редагувати', edit_account_admin_issue_path(issue),
          class: "btn btn-danger pull-right btn-#{ yield(:follow_btn_size) } edit-button"

app/views/issues/_include_map_assets.html.slim
- content_for :map do
  = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css'
  = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js'
  = javascript_include_tag 'leaflet-google.js'
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&libraries=places"

app/views/issues/_issue.html.slim
- unless smart_listing.empty?
  - smart_listing.collection.each do |issue|
    section.post
      .row
        .media.issue-container
          .media-left.media-top.col-lg-4.col-md-5.col-sm-5.custom-img
            = link_to issue
              = image_tag issue.first_attached_image, class: 'img-responsive'
          .media-body-fix.col-lg-8.col-md-7.col-sm-7
            h3.custom-heading
              = link_to issue
                = truncate("#{issue.title}", length: 50)
            .clearfix.row
              p.author-category.col-md-7.col-sm-7.col-xs-12
                span.author Автор:
                span  #{issue.user.full_name }
                br
                span  #{'Категорія: '}
                = link_to issue.category.name, category_path(issue.category)
              p.date-comments.info-group-wrapper.col-md-5.col-sm-5.col-xs-12
                i.fa.fa-calendar-o
                span  #{issue.created_at.strftime("%d/%m/%Y %H:%M")}
                br
                i.fa.fa-location-arrow
                span  #{issue.location}
            p.issue-description
              = truncate("#{issue.description}", length: 130)
  .text-center
    = smart_listing.paginate
    = smart_listing.pagination_per_page_links
- else
  p Нічого не знайдено

app/views/issues/_issues_carousel.html.slim
.project.owl-carousel.owl-theme id='issue-carousel'
  - @attachments.each do |issue_attachment|
    = image_tag issue_attachment.attachment, class: 'img-responsive'

app/views/issues/_moderate_panel.html.slim
.control_status_panel
  - if @issue.pending? && (current_user.admin? || current_user.moderator?)
    = status_control_link('Підтвердити', approve_account_admin_issue_path(@issue), 'success')
    = status_control_link('Відхилити', decline_account_admin_issue_path(@issue), 'danger')
  - if @issue.opened? && current_user.can_close?(@issue)
    = status_control_link('Закрити',close_account_admin_issue_path, 'success')


/modal
#change_status_form.modal.fade role="dialog"
  .modal-dialog
    /! Modal content
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title Підтвердіть зміну статусу
      .modal-body
        = simple_form_for @event, url: '#', authenticity_token: true,
                html: { method: :patch, id: 'add_event_description' } do |f|
          = f.input :description, label: 'Опис',
                  placeholder: 'Обґрунтування зміни статусу',
                  input_html: {maxlength: 2000}
          #event_atachments
            = f.file_field :image, as: :file, label: 'Додати зображення',
                    data: { max_file_size: 8.megabytes }
            img#img_prev.img-thumbnail.hidden alt=('Завантажене зображення') height="300" src="#" width="300" /

          .modal-footer
            = f.button :submit, 'Підтвердити', class: 'btn btn-success',
                    id: 'submit-event'
            button.btn.btn-default data-dismiss="modal" type="button"  Відмінити

javascript:
    $(document).ready(function () { init_change_status_form() });

app/views/issues/_relevant_issues.html.slim
section.relevant
  .heading
    h3 Схожі звернення
  .row.media-section
    - @relevant_issues.each do |relevant_issue|
      .col-sm-6.col-md-3
        .box-image-text.blog
          .top
            .image
              = image_tag relevant_issue.first_attached_image, class: 'img-responsive'
            .bg
            .text
              .buttons
                = link_to 'Читати далі', relevant_issue, class: 'btn btn-template-transparent-primary'
          .content
            h4.short
              = link_to relevant_issue.title, relevant_issue

app/views/issues/_votes.html.slim
- if @voted.empty?
  = link_to upvote_issue_path(@issue), method: :post do
    i.fa.fa-thumbs-o-up aria-hidden='true' title='Підтримати'
- else
  = link_to downvote_issue_path(@issue), method: :delete do
    i.fa.fa-thumbs-up aria-hidden='true' title='Скасувати підтримку'
span.badge.pull-right #{@issue.votes.count}

app/views/issues/followees.html.slim
#heading-breadcrumbs
  .container
    .row.flex-row
      .col-md-7.col-sm-7.col-xs-7
        h2=title 'Відслідковувані звернення'
      .col-md-5.col-sm-5.col-xs-5
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Відслідковувані звернення
#content
  .container
    section
      .row
        .col-md-12
          - provide(:follow_btn_size, 'xs')
          - if current_user.followees_count > 0
              .table-responsive
                table.table.table-hover
                  thead
                    tr
                      th Звернення
                      th Назва
                      th Дата створення
                      th Статус
                      th Дія

                  tbody
                    - @issues.each do |issue|
                      tr
                        td &#8470; #{issue.id}
                        td = issue.title
                        td = l issue.created_at, format: :long
                        td = get_stylized_status_style(issue.status, issue.status_name)
                        td
                          = link_to 'Переглянути', issue_path(issue),
                                  class: 'btn btn-primary btn-xs'
                          = render 'shared/follow_link', issue: issue

          - else
            h3 Ви поки не слідкуєте за жодним зверненням...
            = link_to 'Переглянути усі', issues_path, class: 'btn btn-primary'

app/views/issues/index.html.slim
= render 'issues/breadcrumbs_index'
#content
  .container.zero-padding
    .row
      #blog-listing-medium.col-md-9.col-xs-12
        section
          = smart_listing_render(:issues)
      .col-md-3.col-xs-12.mobile-container
        .panel.panel-default.sidebar-menu.search-bar
          .panel-heading
            h3.panel-title Пошук
          .panel-default
            = render 'shared/search'
        = render 'shared/categories_side_bar'

app/views/issues/index.js.erb
<%= smart_listing_update :issues %>

app/views/issues/map.html.slim
= render 'include_map_assets'
#heading-breadcrumbs
  .container
    .row.flex-row
      .col-md-7.col-sm-7.col-xs-7
        h2=title  'Карта звернень'
      .col-md-5.col-sm-5.col-xs-5
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Карта звернень
#content
  .container
    section
      .row
        .col-md-12
          p.lead=description 'На цій сторінці ви можете переглянути усі звернення, накладені на карту міста'
          #map-container.issues-map
javascript:
  $(document).ready(initIssuesMap);

app/views/issues/new.html.slim
= render 'include_map_assets'
#heading-breadcrumbs
  .container
    .row.flex-row
      .col-md-7.col-sm-7.col-xs-7
        h2=title  'Надіслати нове звернення'
      .col-md-5.col-sm-5.col-xs-5
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Hове звернення
#content
  #contact.container
    section
      .row
        .col-md-8.col-md-offset-2
          = simple_form_for @issue, html: {multipart: true} ,
                                url: issues_path do |f|
            = f.error_messages
            = f.input :name, label: 'Ваше Ім\'я',
                    placeholder: 'Петро Петрович Петренко'
            = f.input :address, label: 'Ваша адреса',
                    placeholder: 'вул. Грушевського 21'
            = f.input :phone, label: 'Номер телефону'
            = f.input :email, as: :email, label: 'Email',
                    placeholder: 'user@domain.com'
            = f.input :title, label: 'Короткий опис проблеми'
            = f.association :category, collection: Category.ordered_by_name,
                    label: 'Категорія'
            = f.input :description, as: :text, label: 'Текст звернення'
            #issue_attachments
              = simple_fields_for :issue_attachments do |ia|
                = link_to_add_association 'Додати зображення', f, :issue_attachments, class: 'btn btn-template-main'
            br
            = f.input :location, label: 'Адреса проблеми',
                    placeholder: 'Івано-Франківськ, Сахарова, 33'
            #map-container.issue-map
            = f.button :submit, 'Надіслати звернення', class: 'btn btn-template-primary'
javascript:
  $('document').ready(function(){
    $("#issue_phone").mask("+38(999)-999-9999");
    newIssueMap();
  });

app/views/issues/show.html.slim
= render 'include_map_assets'
- provide(:follow_btn_size, 'sm')
= render 'breadcrumbs_show'
#content
  .container
    .row
      .col-md-6.col-sm-6.col-xs-6
        p.text-muted.text-uppercase.mobile-font
          span.author Автор: #{@issue.name}
          br
          span Категорія:
          = link_to " #{@issue.category.name}", category_path(@issue.category)
        -if current_user.admin? || current_user.moderator? || current_user.can_close?(@issue)
          = render 'issues/moderate_panel'
      .info-group-wrapper.col-md-6.col-sm-6.col-xs-6
        .follow-wrapper
          .follow.pull-right
            .addthis_sharing_toolbox
            - if user_signed_in? && current_user.active?
              = render 'shared/follow_link', issue: @issue
              = render 'edit_link', issue: @issue
            .followers-count
              span Слідкують:
              span.badge.pull-right #{@issue.followers_count}
    .row
      .col-md-6.col-sm-6.col-xs-8
        p.date-comments
          span
            i.fa.fa-calendar-o
            span  #{time_ago_in_words(@issue.created_at)} тому
          br
          span
            i.fa.fa-location-arrow
            span  #{@issue.location}
      .votes-wrapper.col-md-6.col-sm-6.col-xs-4
        .votes
          - if user_signed_in? && current_user.active?
            = render 'votes'
    section.blog-post
      .row.media-section
        .col-lg-7.col-md-6.col-sm-12.col-xs-12
          #map-container.issue-map
        .col-lg-5.col-md-6.col-sm-12.col-xs-12
          = attachment_carousel(@issue)
    .row
      .col-md-12
        .heading
          h3 Проблема:
        p.word-break.lead= description "#{@issue.description}"

    - if @events.any?
            = render 'issues/events/events'
    section.blog-post
      - if @relevant_issues.any?
        = render 'relevant_issues'
      = render 'comments/comments', commentable: @issue

javascript:
  $(document).ready(function(){
    // initIssuesMap(false, #{@issue.latitude}, #{@issue.longitude});
    showIssueMap(#{@issue.latitude}, #{@issue.longitude});
    $("#issue-carousel").owlCarousel({
        nav : true,
        items : 1,
        autoplay: true,
        loop: true,
        autoplayTimeout: 3000,
        autoplayHoverPause: true
    });
  });