config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' },
             skip: [:sessions]

  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign-in', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :account do
    namespace :admin do
      resources :issues, only: [:index, :edit, :update] do
        member do
          patch :approve, :decline, :close
        end
      end

      resources :users, only: [:index] do
        member do
          patch :toggle_ban
          patch :change_role
        end
      end

      resources :categories
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server, at: '/resque'
  end

  resources :categories, only: [:show]

  resources :issues, only: [:new, :index, :create, :show] do
    collection do
      get :map
      get :closed
    end
    member do
      get :popup
      post :upvote
      delete :downvote
    end
    post 'follow',   to: 'issues/socializations#follow'
    post 'unfollow', to: 'issues/socializations#unfollow'
    resources :comments, module: :issues, only: [:create, :index]
  end

  resources :comments, only: [:destroy]
  resources :users, only: [:show] do
    collection do
      get :ranking
    end
  end

  resources :events, only: [:show]

  get  'followees', to: 'issues#followees'
  get  'feed', to: 'feeds#common_feed'
  get  'user_feed', to: 'feeds#user_feed'
  get  'statistics', to: 'common_pages#statistics'
  get  ':page', to: 'pages#show', as: :static_pages
  root to: 'common_pages#home'
end

app/views/shared/_categories.html.slim
- @categories.each do |category|
  li
    = link_to category_path(category)
      .category-item
        .issue-category
          = category.name
        .category-badge
          span.badge
            = category.issues.approved.count

app/views/shared/_categories_side_bar.html.slim
.panel.panel-default.sidebar-menu
  .panel-heading.categories-heading
    h3.panel-title Категорії
  .container-fluid
    .categoties-toggle.navbar-toggle.collapsed.pull-left type="button" data-toggle="collapse" data-target="#category-nav-list"
      .btn.btn-sm.btn-default.btn-template-main
        span Категорії
  #category-nav-list.collapse
    .panel-default
      ul.nav.nav-pills.nav-stacked.row
        = render 'shared/categories', collection: @categories

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_follow_link.html.slim
-if !current_user.follows?(issue)
  = link_to 'Слідкувати', issue_follow_path(issue), method: :post,
                      class: "btn btn-info pull-right btn-#{ yield(:follow_btn_size) }"
-elsif current_user.follows?(issue)
  = link_to 'Відписатися', issue_unfollow_path(issue), method: :post,
                      class: "btn btn-warning pull-right btn-#{ yield(:follow_btn_size) }"

app/views/shared/_head.html.slim
head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
  meta name="viewport" content="width=device-width, initial-scale=1" /
  = display_meta_tags
  = csrf_meta_tags
  = render 'shared/favicons'
  = Gon::Base.render_data
  = stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800', media: 'all'
  = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all'
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'https://code.highcharts.com/highcharts.js'
  = javascript_include_tag 'application'
  = yield :map if content_for? :map

app/views/shared/_issue_filters.html.slim
= smart_listing_controls_for(:issues, {class: 'search-controls form-inline text-right'})
  .form-group.status_select
    span Статус:
    = select_tag :issue_status,
            options_for_select(Issue.status_attributes_for_select),
            class: 'form-control',
            prompt: 'Виберіть статус'
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: 'search form-control',
            placeholder: 'Пошук', autocomplete: :off

app/views/shared/_number_of_issues.html.slim
=link_to_if(category.calculate('opened') != 0, category.calculate('opened'), account_admin_category_path(id: category.id, status: 'opened'), title: 'Відкриті')
|  | 
=link_to_if(category.calculate('closed') != 0, category.calculate('closed'), account_admin_category_path(id: category.id, status: 'closed'), title: 'Закриті')
|  | 
=link_to_if(category.calculate('pending') != 0, category.calculate('pending'), account_admin_category_path(id: category.id, status: 'pending'), title: 'На модерації')
|  | 
=link_to_if(category.calculate('declined') != 0, category.calculate('declined'), account_admin_category_path(id: category.id, status: 'declined'), title: 'Відхилені')

app/views/shared/_search.html.slim
= smart_listing_controls_for(:issues)
  .input-group
    = text_field_tag :filter, '', class: 'form-control',
            placeholder: 'Пошук', autocomplete: :off
    = hidden_field_tag 'status', @status
    span.input-group-btn
      = content_tag :button, type: 'submit', class: 'btn btn-template-main'
        i.fa.fa-search

app/views/shared/feed.html.slim
#heading-breadcrumbs
  .container
    .row
      .col-md-7.col-sm-6
        h2 Останні оновлення
      .col-md-5.col-sm-6
        ul.breadcrumb
          li= link_to 'На головну', root_path
          li Останні оновлення
#content.feed
  .container
    .row
      #blog-listing-medium.col-md-9
        section.container.events_list.loaded_data_container
        #loader-block.col-xs-12.hidden
          = image_tag 'loader.gif', alt: 'Loader', id: 'loader-img',
                  class: 'img-responsive col-xs-2 col-xs-offset-5'

javascript:
    $('document').ready(init_infinity_scroll(1, window.location.href, true));

- if users_feed?
  javascript:
      $('document').ready(init_users_feed_page());