config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' },
             skip: [:sessions]

  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign-in', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  namespace :account do
    namespace :admin do
      resources :issues, only: [:index, :edit, :update] do
        member do
          patch :approve, :decline, :close
        end
      end

      resources :users, only: [:index] do
        member do
          patch :toggle_ban
          patch :change_role
        end
      end

      resources :categories
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server, at: '/resque'
  end

  resources :categories, only: [:show]

  resources :issues, only: [:new, :index, :create, :show] do
    collection do
      get :map
      get :closed
    end
    member do
      get :popup
      post :upvote
      delete :downvote
    end
    post 'follow',   to: 'issues/socializations#follow'
    post 'unfollow', to: 'issues/socializations#unfollow'
    resources :comments, module: :issues, only: [:create, :index]
  end

  resources :comments, only: [:destroy]
  resources :users, only: [:show] do
    collection do
      get :ranking
    end
  end

  resources :events, only: [:show]

  get  'followees', to: 'issues#followees'
  get  'feed', to: 'feeds#common_feed'
  get  'user_feed', to: 'feeds#user_feed'
  get  'statistics', to: 'common_pages#statistics'
  get  ':page', to: 'pages#show', as: :static_pages
  root to: 'common_pages#home'
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @issues = Issue.approved.ordered
    @issues_feed = @issues.first(4)
    @count = Issue.approved.count
    @closed_count = Issue.closed.count
  end
end

app/views/home/index.html.slim
section.no-mb
  .jumbotron
    .dark-mask
    .container
      .row.mb-small
        .col-sm-12.text-center
          h1 Hello, Франківськ!
          h2 До вашої уваги соціальний проект під кодовою назвою "NewVasjuky" групи IF-070.WebUI-RoR
      .row
        .col-md-6.col-sm-12
          p З допомогою цього додатка можна у кілька кліків надіслати звернення для вирішення різноманітних комунальних проблем з будь-якого пристрою: смартфона, планшета, комп'ютера.
        .col-md-6.col-sm-12
          = link_to 'Повідомити про проблему', new_issue_path, class: 'scroll-to btn btn-lg btn-template-transparent-black'
section.bar.background-pentagon.no-mb
  .container
    .row.showcase
      .col-sm-6
        .item
          .icon
            i.fa.fa-question
          h4
            span.counter #{@count}
            br
            = link_to 'звернень надіслано', issues_path
      .col-sm-6
        .item
          .icon
            i.fa.fa-check
          h4
            span.counter #{@closed_count}
            br
            = link_to 'проблем вирішено', issues_path
section.bar.background-white.no-mb
  .container
    .col-md-12
      .heading.text-center
        h2 Останні додані:
      .row
      - @issues_feed.each do |issue|
        .col-md-3.col-sm-6
          .box-image-text.blog
            .top
              .image
                = image_tag issue.first_attached_image, class: 'img-responsive'
              .bg
              .text
                .buttons
                  = link_to 'Читати далі', issue, class: 'btn btn-template-transparent-primary'
            .content
              p.author-category
                = link_to issue.category.name, category_path(issue.category)
              h4
                = link_to issue.title, issue

app/views/home/index.slim
h1 New Vasjuky Project

- if current_user.nil?
  = link_to 'Sign in with Facebook', user_facebook_omniauth_authorize_path
- else
  ul
    li
      |Name:  #{current_user.name}
    li
      |Email: #{current_user.email}
  = link_to('Logout', destroy_user_session_path, :method => :delete)

- if current_user && current_user.admin?
  div
    = link_to 'All users', account_users_path